<?php
$designations = [
    "Accounts Manager",
    "Accounts officer",
    "Assistant",
    "Assistant Professor",
    "Auditor",
    "Branch Manager",
    "Broadcaster",
    "Certified Ethical Hacker",
    "Chairman",
    "Chief Executive Officer",
    "Chief Financial Officer",
    "Clerk",
    "Consultant",
    "Database Administrator",
    "Dentist",
    "Director",
    "Doctor",
    "Educationist",
    "Engineer",
    "Finance Administrator",
    "Finance Manager",
    "Freelancer",
    "General Manager",
    "HR Manager",
    "Insurance Counselor",
    "Internee",
    "Jr. Associate",
    "Jr. Officer",
    "Lecturer",
    "Managing Director",
    "Marketing Officer",
    "Owner",
    "Physical Therapist",
    "Principal",
    "Professional Engineer",
    "Receptionist",
    "Registered Nurse",
    "RO Relationship Officer",
    "Self Employed",
    "Senior Chef",
    "Software Consultant",
    "Sr. Associate",
    "Sr. Officer",
    "Sr. Vice president",
    "SRO Senior Relationship Officer",
    "Student",
    "Student Counselor",
    "Teacher",
    "Team Leader",
    "TL Team Leader",
    "Web Designer",
    "Web Developer"
];
$jobs = [
    "Administration Officer",
    "Air Hostess",
    "Architect",
    "Artist",
    "Assistant Professor",
    "Associate Professor",
    "Auditor",
    "Banker",
    "Braodcaster",
    "Business",
    "Chef",
    "Civil Engineer",
    "Clerical Official",
    "Commercial Pilot",
    "Company Secretary",
    "Computer Professional",
    "Consultant",
    "Contractor",
    "Cook",
    "Cost Accountant",
    "Creative Person",
    "Customer Support Professional",
    "Defense Employee",
    "Dentist",
    "Designer",
    "Digital Marketing",
    "Doctor",
    "Doctor of Nutrition",
    "E Commerce",
    "Economist",
    "Engineer",
    "Engineer (Aviation)",
    "Engineer (Chemical)",
    "Engineer (Electrical)",
    "Engineer (Mechanical)",
    "Engineer (Project)",
    "Entertainment Professional",
    "Event Manager",
    "Executive",
    "Factory worker",
    "Farmer",
    "Fashion Designer",
    "Finance Professional",
    "Fitness Trainer",
    "Flight Attendant",
    "Freelancer",
    "Government Employee",
    "Head Master",
    "Head Mistress",
    "Health Care Professional",
    "Home Maker",
    "Hotel & Restaurant Professional",
    "Human Resources Professional",
    "Interior Designer",
    "Investment Professional",
    "IT / Telecom Professional",
    "Jobless",
    "Journalist",
    "Judge",
    "Lab Incharge",
    "Lawyer",
    "Lecturer",
    "Legal Professional",
    "Manager",
    "Marketing Professional",
    "Media Professional",
    "Medical Professional",
    "Medical Transcriptionist",
    "Merchant Naval Officer",
    "Nothing",
    "Nurse",
    "Occupational Therapist",
    "Optician",
    "Others",
    "Pharmacist",
    "Physician Assistant",
    "Physicist",
    "Physiotherapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Politician",
    "Production professional",
    "Professor",
    "Professor",
    "Psychologist",
    "Public Relations Professional",
    "Real Estate Professional",
    "Research Scholar",
    "Retail Professional",
    "Retired",
    "Retired Person",
    "Sales Professional",
    "Scientist",
    "Security Gaurd",
    "Self-employed Person",
    "Social Media marketing",
    "Social Worker",
    "Software Consultant",
    "Software Engineer",
    "Sportsman",
    "Student",
    "Student Counselor",
    "Tailor",
    "Teacher",
    "Team Leader",
    "Technician",
    "Training Professional",
    "Transportation Professional",
    "Veterinary Doctor",
    "Volunteer",
    "Writer",
    "Zoologist"
];
$educations = [
    "A Level",
    "A Level",
    "ACCA",
    "ACMA",
    "Alma Fazila",
    "Associate Degree",
    "B Arch",
    "B Com",
    "B Phil",
    "B Plan",
    "B Sc. Honors",
    "B Tech",
    "B.Pharm",
    "BA",
    "Bachelor Of Law",
    "Bachelor Of Veterinary Science",
    "Bachelors in Food Science and Technology",
    "BAFD",
    "BAMS",
    "BBA",
    "BCA",
    "BCS",
    "BDS",
    "BE",
    "BEd",
    "BFA",
    "BFM (Financial Management)",
    "BGL",
    "BHM",
    "BHMS",
    "BLIS",
    "BMM (MASS MEDIA)",
    "BPT",
    "BS Accounting",
    "BS Aviation",
    "BS Bio Informatics",
    "BS Botany",
    "BS Economics",
    "BS English Literature",
    "BS Fashion Designing",
    "BS Fashion Marketing",
    "BS Finance",
    "BS Finance and IT",
    "BS Honors",
    "BS Human Resource",
    "BS Imaging Technology",
    "BS IT",
    "BS Liberal Arts",
    "BS Mass Communication",
    "BSc Computer Science",
    "BSc IT",
    "BSc Nursing",
    "BSc. Accounting and Finance",
    "BSc. Aviation",
    "BSc. Bio Informatics",
    "BSc. Biomedical",
    "BSc. Electronics Engineering",
    "BSc. Engineering",
    "BSc. Health Sciences",
    "BSc. Home Economics",
    "BSc. Honors",
    "BSc. Mass Communication",
    "BSc. Mathematics",
    "BSc. Psychology",
    "BSc. Social Work",
    "BSc. Statistics and Economics",
    "BSc. Textile Designing",
    "BSc. Textile Engineering",
    "BSCS",
    "BSW",
    "CA (Chartered Accountant)",
    "CA Final",
    "CA Inter",
    "CFA (Chartered Financial Analyst)",
    "CGA",
    "CIMA",
    "Company Secretary (CS)",
    "CPA",
    "CSS",
    "D Pharmacy",
    "DDNS - Doctor of Dietary Nutritionist",
    "Degree In Medicine",
    "DIL (UK)",
    "Diploma",
    "Diploma In Nursing",
    "DM - Doctorate Of Medicine",
    "DMIS",
    "DMLS",
    "Doctor of Dermal Sciences - DDS",
    "Doctor of Homeo Pathy",
    "Doctor of Human Nutrition and diets - DHND",
    "Doctor of Optometry",
    "Doctor of Physio Therapy",
    "DVM",
    "F. Sc.",
    "FA",
    "FCCA",
    "FCPS",
    "Flying Diploma",
    "Flying Diploma",
    "Flying Diploma",
    "High School",
    "High School",
    "I.Com",
    "IAS",
    "ICS",
    "ICWA",
    "IPS",
    "Less Than High School",
    "LLB",
    "LLM",
    "M Arch",
    "M Com",
    "M Phil",
    "M Sc",
    "M Sc. Environmental Science",
    "M Sc. Geography",
    "M Tech",
    "M.Pharm",
    "M.Phil",
    "MA",
    "MA Accounting",
    "MA Education",
    "MA Political Science",
    "MAMS",
    "Master in Accounting and Finance",
    "Master in Health Sciences",
    "Master In Medicine",
    "Master in Public Administration",
    "Master in Supply Chain Management",
    "Master Of Law",
    "Master Of Veterinary Science",
    "Matriculation",
    "MBA",
    "MBBS",
    "MBF",
    "MBSM",
    "MCA",
    "MCh - Master Of Chirurgiae",
    "MCS",
    "MD",
    "MD / MS (Medical)",
    "MDLT",
    "MDS",
    "ME",
    "MEd",
    "Medical Esthetician Diploma",
    "Medical Laboratory Technology",
    "MFM (Financial Management)",
    "MHM",
    "MHMS",
    "MID",
    "MLIS",
    "MPA",
    "MPT",
    "MRCS",
    "MS Cliical psychology",
    "MS Cliical psychology",
    "MS Computer Science",
    "MS Electrical Engineering",
    "MS Environmental Science",
    "MS Finance and Accounting",
    "MS IT",
    "MS Management",
    "MS Marketing",
    "MS Mechanical engineering",
    "MS Nuclear Engineering",
    "MS Robotics Engineering",
    "MS. Electronics Engineering",
    "MSc Computer Science",
    "MSc IT",
    "MSc Nursing",
    "MSc.",
    "MSc. Architecture",
    "MSc. Biology",
    "Msc. Botany",
    "MSc. Chemistry",
    "MSc. Economics",
    "Msc. Engineering",
    "MSc. Geology",
    "MSc. Interior Design",
    "MSc. Mass Communication",
    "MSc. Mathematics",
    "MSc. Physics",
    "MSc. Psychology",
    "MSc. Statistics",
    "MSc. Zoology",
    "MSW",
    "O Level",
    "Other Education",
    "PGDCA",
    "PGDM",
    "Ph D",
    "PLAB",
    "Polytechnic",
    "QLD (UK)",
    "Safety Engineer",
    "Software Engineer",
    "Telecommunication Engineering",
    "Under Matric",
    "US Residency"
];
$ages = [
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65
];
$weights = [
    "Below 40 kg",
    "40 kg",
    "41 kg",
    "42 kg",
    "43 kg",
    "44 kg",
    "45 kg",
    "46 kg",
    "47 kg",
    "48 kg",
    "49 kg",
    "50 kg",
    "51 kg",
    "52 kg",
    "53 kg",
    "54 kg",
    "55 kg",
    "56 kg",
    "57 kg",
    "58 kg",
    "59 kg",
    "60 kg",
    "61 kg",
    "62 kg",
    "63 kg",
    "64 kg",
    "65 kg",
    "66 kg",
    "67 kg",
    "68 kg",
    "69 kg",
    "70 kg",
    "71 kg",
    "72 kg",
    "73 kg",
    "74 kg",
    "75 kg",
    "76 kg",
    "77 kg",
    "78 kg",
    "79 kg",
    "80 kg",
    "81 kg",
    "82 kg",
    "83 kg",
    "84 kg",
    "85 kg",
    "86 kg",
    "87 kg",
    "88 kg",
    "89 kg",
    "90 kg",
    "91 kg",
    "92 kg",
    "93 kg",
    "94 kg",
    "95 kg",
    "96 kg",
    "97 kg",
    "98 kg",
    "99 kg",
    "100 kg",
    "Above 100 kg"
];

$heights = [
    "Below 4ft",
    "4ft 1in",
    "4ft 2in",
    "4ft 3in",
    "4ft 4in",
    "4ft 5in",
    "4ft 6in",
    "4ft 7in",
    "4ft 8in",
    "4ft 9in",
    "4ft 10in",
    "4ft 11in",
    "5ft",
    "5ft 1in",
    "5ft 2in",
    "5ft 3in",
    "5ft 4in",
    "5ft 5in",
    "5ft 6in",
    "5ft 7in",
    "5ft 8in",
    "5ft 9in",
    "5ft 10in",
    "5ft 11in",
    "6ft",
    "6ft 1in",
    "6ft 2in",
    "6ft 3in",
    "6ft 4in",
    "6ft 5in",
    "6ft 6in",
    "6ft 7in",
    "6ft 8in",
    "6ft 9in",
    "6ft 10in",
    "6ft 11in",
    "7ft",
    "Above 7ft"
];





$countries_names = [
    "Pakistan",
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua And Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote D'Ivoire (Ivory Coast)",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji Islands",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia The",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey and Alderney",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Hong Kong S.A.R.",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau S.A.R.",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Man (Isle of)",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Palau",
    "Palestinian Territory Occupied",
    "Panama",
    "Papua new Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Island",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Pierre and Miquelon",
    "Saint Vincent And The Grenadines",
    "Saint-Barthelemy",
    "Saint-Martin (French part)",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard And Jan Mayen Islands",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "The Bahamas",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad And Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks And Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City State (Holy See)",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (British)",
    "Virgin Islands (US)",
    "Wallis And Futuna Islands",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];
$states = [
    "Punjab",
    "Sindh",
    "Khyber Pakhtunkhwa",
    "Balochistan",
    "Islamabad Capital Territory",
    "Gilgit-Baltistan",
    "Azad Kashmir"
];
$cities = [
    "Lahore",
    "Rawalpindi",
    "Karachi",
    "Islamabad",
    "Faisalabad",
    "Multan",
    "Peshawar",
    "Quetta",
    "Sialkot",
    "Gujranwala",
    "Sargodha",
    "Bahawalpur",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Rahim Yar Khan",
    "Mardan",
    "Kasur",
    "Okara",
    "Dera Ghazi Khan",
    "Gujrat",
    "Jhang",
    "Mingora",
    "Chiniot",
    "Wah Cantt",
    "Kamoke",
    "Muzaffargarh",
    "Sahiwal",
    "Kohat",
    "Dera Ismail Khan",
    "Nawabshah",
    "Jacobabad",
    "Chitral",
    "Hangu",
    "Karak",
    "Hyderabad",
    "Abbottabad",
    "Gilgit",
    "Skardu",
    "Turbat",
    "Gwadar",
    "Khuzdar",
    "Zhob",
    "Chaman",
    "Hub",
    "Khairpur",
    "Shikarpur",
    "Ghotki",
    "Kashmore",
    "Thatta",
    "Badin",
    "Tando Adam",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Umerkot",
    "Mirpur Khas",
    "Dadu",
    "Matiari",
    "Sanghar",
    "Jamshoro",
    "Vehari",
    "Pakpattan",
    "Lodhran",
    "Khanewal",
    "Bhakkar",
    "Mianwali",
    "Narowal",
    "Attock",
    "Chakwal",
    "Jhelum",
    "Hafizabad",
    "Nankana Sahib",
    "Toba Tek Singh",
    "Haripur",
    "Mansehra",
    "Battagram",
    "Swabi",
    "Charsadda",
    "Dir",
    "Timergara",
    "Bannu",
    "Tank",
    "Lakki Marwat",
    "Shangla",
    "Upper Dir",
    "Lower Dir",
    "Hunza",
    "Ghanche",
    "Astore",
    "Ghizer",
    "Muzaffarabad",
    "Mirpur",
    "Kotli",
    "Bagh",
    "Rawalakot"
];
$areas = [
    "Lalkurti, Saddar",
    "near civil hospital Daska",
    "Abdullah Pur Colony",
    "Abdullah Town",
    "BOR society",
    "civil Area Okara Cantt",
    "depal pur",
    "Dream Avenue",
    "gulraiz 2",
    "Khayaban E Amin",
    "kot radha kishan",
    "Muhafiz Town",
    "Officers Colony",
    "River Gardens housing society",
    "Shahkot",
    "upper mall",
    "upper mall, habibullah road",
    "10 marla",
    "24",
    "29",
    "2nd House Gulshan-e-Ravi",
    "30",
    "30gujranwala",
    "38",
    "4 kanal",
    "43380",
    "452 GB",
    "5",
    "80 Marla",
    "Aab Para housing Society",
    "Aabpara housing Society Canal road, Lahore",
    "Aashyana scheme",
    "Abbottabad",
    "Abdalian Society Lahore",
    "Abdullah Pur",
    "Abdullah Town near Margzar Society",
    "Adyala",
    "Adyalla road near Defense road",
    "Ahmad Garden",
    "Ahmadpur East",
    "Aiman Abad Road",
    "airport housing society",
    "Aitchion society",
    "Akhtarabad",
    "Al Hamd Colony",
    "Al Jalil Garden",
    "Al Makkah society",
    "Al Noor city",
    "Al Raheem Garden",
    "Al Rehman Garden Phase 2",
    "Al Rehman Garden Phase IV",
    "Al-Nafay housing colony",
    "alam chowk",
    "Alfateh city",
    "Ali Razaabad",
    "Ali view park",
    "Allama Iqbal Town",
    "Architect Society",
    "Army Housing Society",
    "Army Officers Colony",
    "Ashiana Housing Scheme",
    "Askari 10",
    "Askari 11",
    "Audit and Accounts Society",
    "Awan town",
    "AWT",
    "Azeemabad",
    "Badami bagh",
    "Badian Road",
    "Baghban Pura",
    "Bahria Enclave",
    "Bahria Extension",
    "Bahria orchard",
    "Bahria Town",
    "Bankers Society Badian Road",
    "Bismillah Housing Society",
    "Bosan road Multan",
    "Bukhari Colony",
    "Burewala",
    "Canal Bank Housing Society",
    "Canal City",
    "Canal Garden Lahore",
    "Canal road",
    "Canal View Housing Society",
    "Cavalry Ground",
    "Central Park Housing Society",
    "Chak Shahzad",
    "Chaklala Scheme 3",
    "Chakwal",
    "Chashma",
    "Chauburji",
    "City Housing Scheme",
    "City Shopping Centre",
    "Civil lines",
    "Civil Town",
    "college road",
    "DHA",
    "DHA Phase 1",
    "DHA Phase 4",
    "DHA Phase 6",
    "DHA Phase 7",
    "DHA Phase 8",
    "DHA Phase 9",
    "DHA Rahbar",
    "Dream Garden",
    "Eden",
    "Edenabad",
    "Faisal Town",
    "Falcon City Lahore",
    "Formanites Housing Society",
    "Garden Town",
    "Ghori town",
    "Green Town",
    "Gulberg 2",
    "Gulberg 3",
    "Gulshan-e-Ravi",
    "Gulshan Iqbal",
    "Gulshan Colony",
    "Gulzar E Quaid",
    "Harbanspura",
    "Ichhra",
    "Iqbal Town",
    "Islamabad",
    "Johar Town",
    "Jubilee Town",
    "Judicial Housing Society",
    "Karachi",
    "Kashmir road",
    "Kharian",
    "Kot Addu",
    "Lahore",
    "Lahore Cantt",
    "Lake City",
    "LDA Avenue 1",
    "Madina Town",
    "Malir",
    "Model Town",
    "Multan Cantt",
    "Multan Road Lahore",
    "Muslim Town",
    "Mustafa Town",
    "Nankana Sahib",
    "Nawab Town",
    "Nazimabad",
    "New Lahore City",
    "NFC Housing Society Lahore",
    "Nishtar Colony",
    "North Nazimabad",
    "Okara",
    "OPF Society Lahore",
    "Pak Arab Housing Society",
    "Paragon City",
    "Park View Society",
    "PCSIR Phase 2",
    "PIA Housing Society",
    "Punjab Cooperative Housing Society",
    "Qasimabad",
    "Quaid e Azam Town",
    "Raiwind",
    "Rawalpindi",
    "Rawalpindi Cantt",
    "Rehman Garden",
    "Sabzazar",
    "Saddar",
    "Samanabad",
    "Satellite Town",
    "Shadman",
    "Shahdara",
    "Shalimar",
    "Sheikhupura",
    "Soan Garden",
    "State Life Housing Society",
    "Sukh Chain Society",
    "Sukkur",
    "Sultan Pura",
    "Surjani Town",
    "Taj Bagh",
    "Taxila",
    "Thokar Niaz Baig",
    "Township",
    "UET Society Lahore",
    "Valencia Town",
    "Wahdat Road",
    "Walton Road",
    "Wapda Town",
    "Wapda Town Phase 2",
    "Yaseen Town",
    "Zaman Park"
];
$countries = [
    ["name" => "Afghanistan", "code" => "+93", "flag" => "🇦🇫"],
    ["name" => "Albania", "code" => "+355", "flag" => "🇦🇱"],
    ["name" => "Algeria", "code" => "+213", "flag" => "🇩🇿"],
    ["name" => "Andorra", "code" => "+376", "flag" => "🇦🇩"],
    ["name" => "Angola", "code" => "+244", "flag" => "🇦🇴"],
    ["name" => "Argentina", "code" => "+54", "flag" => "🇦🇷"],
    ["name" => "Armenia", "code" => "+374", "flag" => "🇦🇲"],
    ["name" => "Australia", "code" => "+61", "flag" => "🇦🇺"],
    ["name" => "Austria", "code" => "+43", "flag" => "🇦🇹"],
    ["name" => "Azerbaijan", "code" => "+994", "flag" => "🇦🇿"],

    ["name" => "Bahrain", "code" => "+973", "flag" => "🇧🇭"],
    ["name" => "Bangladesh", "code" => "+880", "flag" => "🇧🇩"],
    ["name" => "Belarus", "code" => "+375", "flag" => "🇧🇾"],
    ["name" => "Belgium", "code" => "+32", "flag" => "🇧🇪"],
    ["name" => "Belize", "code" => "+501", "flag" => "🇧🇿"],
    ["name" => "Benin", "code" => "+229", "flag" => "🇧🇯"],
    ["name" => "Bhutan", "code" => "+975", "flag" => "🇧🇹"],
    ["name" => "Bolivia", "code" => "+591", "flag" => "🇧🇴"],
    ["name" => "Bosnia and Herzegovina", "code" => "+387", "flag" => "🇧🇦"],
    ["name" => "Botswana", "code" => "+267", "flag" => "🇧🇼"],
    ["name" => "Brazil", "code" => "+55", "flag" => "🇧🇷"],
    ["name" => "Brunei", "code" => "+673", "flag" => "🇧🇳"],
    ["name" => "Bulgaria", "code" => "+359", "flag" => "🇧🇬"],

    ["name" => "Cambodia", "code" => "+855", "flag" => "🇰🇭"],
    ["name" => "Cameroon", "code" => "+237", "flag" => "🇨🇲"],
    ["name" => "Canada", "code" => "+1", "flag" => "🇨🇦"],
    ["name" => "Chile", "code" => "+56", "flag" => "🇨🇱"],
    ["name" => "China", "code" => "+86", "flag" => "🇨🇳"],
    ["name" => "Colombia", "code" => "+57", "flag" => "🇨🇴"],
    ["name" => "Costa Rica", "code" => "+506", "flag" => "🇨🇷"],
    ["name" => "Croatia", "code" => "+385", "flag" => "🇭🇷"],
    ["name" => "Cuba", "code" => "+53", "flag" => "🇨🇺"],
    ["name" => "Cyprus", "code" => "+357", "flag" => "🇨🇾"],
    ["name" => "Czech Republic", "code" => "+420", "flag" => "🇨🇿"],

    ["name" => "Denmark", "code" => "+45", "flag" => "🇩🇰"],
    ["name" => "Dominican Republic", "code" => "+1", "flag" => "🇩🇴"],

    ["name" => "Egypt", "code" => "+20", "flag" => "🇪🇬"],
    ["name" => "Estonia", "code" => "+372", "flag" => "🇪🇪"],
    ["name" => "Ethiopia", "code" => "+251", "flag" => "🇪🇹"],

    ["name" => "Finland", "code" => "+358", "flag" => "🇫🇮"],
    ["name" => "France", "code" => "+33", "flag" => "🇫🇷"],

    ["name" => "Germany", "code" => "+49", "flag" => "🇩🇪"],
    ["name" => "Ghana", "code" => "+233", "flag" => "🇬🇭"],
    ["name" => "Greece", "code" => "+30", "flag" => "🇬🇷"],

    ["name" => "Hong Kong", "code" => "+852", "flag" => "🇭🇰"],
    ["name" => "Hungary", "code" => "+36", "flag" => "🇭🇺"],

    ["name" => "Iceland", "code" => "+354", "flag" => "🇮🇸"],
    ["name" => "India", "code" => "+91", "flag" => "🇮🇳"],
    ["name" => "Indonesia", "code" => "+62", "flag" => "🇮🇩"],
    ["name" => "Iran", "code" => "+98", "flag" => "🇮🇷"],
    ["name" => "Iraq", "code" => "+964", "flag" => "🇮🇶"],
    ["name" => "Ireland", "code" => "+353", "flag" => "🇮🇪"],
    ["name" => "Israel", "code" => "+972", "flag" => "🇮🇱"],
    ["name" => "Italy", "code" => "+39", "flag" => "🇮🇹"],

    ["name" => "Japan", "code" => "+81", "flag" => "🇯🇵"],
    ["name" => "Jordan", "code" => "+962", "flag" => "🇯🇴"],

    ["name" => "Kazakhstan", "code" => "+7", "flag" => "🇰🇿"],
    ["name" => "Kenya", "code" => "+254", "flag" => "🇰🇪"],
    ["name" => "Kuwait", "code" => "+965", "flag" => "🇰🇼"],

    ["name" => "Latvia", "code" => "+371", "flag" => "🇱🇻"],
    ["name" => "Lebanon", "code" => "+961", "flag" => "🇱🇧"],
    ["name" => "Libya", "code" => "+218", "flag" => "🇱🇾"],
    ["name" => "Lithuania", "code" => "+370", "flag" => "🇱🇹"],

    ["name" => "Malaysia", "code" => "+60", "flag" => "🇲🇾"],
    ["name" => "Maldives", "code" => "+960", "flag" => "🇲🇻"],
    ["name" => "Mexico", "code" => "+52", "flag" => "🇲🇽"],
    ["name" => "Morocco", "code" => "+212", "flag" => "🇲🇦"],

    ["name" => "Nepal", "code" => "+977", "flag" => "🇳🇵"],
    ["name" => "Netherlands", "code" => "+31", "flag" => "🇳🇱"],
    ["name" => "New Zealand", "code" => "+64", "flag" => "🇳🇿"],
    ["name" => "Nigeria", "code" => "+234", "flag" => "🇳🇬"],
    ["name" => "Norway", "code" => "+47", "flag" => "🇳🇴"],

    ["name" => "Oman", "code" => "+968", "flag" => "🇴🇲"],

    ["name" => "Pakistan", "code" => "+92", "flag" => "🇵🇰"],
    ["name" => "Philippines", "code" => "+63", "flag" => "🇵🇭"],
    ["name" => "Poland", "code" => "+48", "flag" => "🇵🇱"],
    ["name" => "Portugal", "code" => "+351", "flag" => "🇵🇹"],

    ["name" => "Qatar", "code" => "+974", "flag" => "🇶🇦"],

    ["name" => "Romania", "code" => "+40", "flag" => "🇷🇴"],
    ["name" => "Russia", "code" => "+7", "flag" => "🇷🇺"],

    ["name" => "Saudi Arabia", "code" => "+966", "flag" => "🇸🇦"],
    ["name" => "Singapore", "code" => "+65", "flag" => "🇸🇬"],
    ["name" => "South Africa", "code" => "+27", "flag" => "🇿🇦"],
    ["name" => "South Korea", "code" => "+82", "flag" => "🇰🇷"],
    ["name" => "Spain", "code" => "+34", "flag" => "🇪🇸"],
    ["name" => "Sri Lanka", "code" => "+94", "flag" => "🇱🇰"],
    ["name" => "Sweden", "code" => "+46", "flag" => "🇸🇪"],
    ["name" => "Switzerland", "code" => "+41", "flag" => "🇨🇭"],

    ["name" => "Thailand", "code" => "+66", "flag" => "🇹🇭"],
    ["name" => "Turkey", "code" => "+90", "flag" => "🇹🇷"],

    ["name" => "UAE", "code" => "+971", "flag" => "🇦🇪"],
    ["name" => "United Kingdom", "code" => "+44", "flag" => "🇬🇧"],
    ["name" => "United States", "code" => "+1", "flag" => "🇺🇸"],

    ["name" => "Vietnam", "code" => "+84", "flag" => "🇻🇳"],

    ["name" => "Yemen", "code" => "+967", "flag" => "🇾🇪"],
];
$castes = [
    "Abbasi",
    "Abdal",
    "Abidi",
    "Abro",
    "Afridi",
    "Agha",
    "Ahbans",
    "Alavi",
    "Alizai",
    "Alpial",
    "Alvi",
    "Amir",
    "Ansari",
    "Arabs",
    "Arain",
    "Arghon",
    "Ashkani",
    "Askari",
    "Assamese",
    "Atcha",
    "Atishbaz",
    "Attar",
    "Attarwala",
    "Awan",
    "Bachgoti",
    "Badinij",
    "Bafan",
    "Baghban",
    "Bahawalanzai",
    "Bahmani",
    "Baig",
    "Bajwa",
    "Bakho",
    "Baloch",
    "Balti",
    "Baluch",
    "Bandhmati",
    "Bangash",
    "Bangial",
    "Bangulzai",
    "Banjara",
    "Bannu",
    "Banuchi",
    "Baqri",
    "Barazani",
    "Barelvi",
    "Barhai",
    "Barlas",
    "Barr",
    "Basra",
    "Beary",
    "Behlim",
    "Behna",
    "Bengali",
    "Bhabra",
    "Bhadala",
    "Bhale",
    "Bhand",
    "Bhangra",
    "Bharbhunja",
    "Bhatia",
    "Bhatiara",
    "Bhatti",
    "Bhili",
    "Bhishti",
    "Bhumihar",
    "Bhutta",
    "Bijarani",
    "Bisati",
    "Bisen",
    "Bizenjo",
    "Bodla",
    "Brahmani",
    "Bukhari",
    "Buledi",
    "Bulfati",
    "Burig",
    "Buriro",
    "Burki",
    "Butt",
    "Buzdar",
    "Catholic",
    "Chachar",
    "Chadwa",
    "Chagatai",
    "Chamail",
    "Chamkanni",
    "Chandel",
    "Chandio",
    "Changwani",
    "Channa",
    "Chaudhry",
    "Chauhan",
    "Chaush",
    "Chechi",
    "Cheetah",
    "Chhaparband",
    "Chhipa",
    "Chik",
    "Chishti",
    "Chudhary",
    "Chughtai",
    "Chunara",
    "Chundrigar",
    "Churihar",
    "Chutani",
    "Dafali",
    "Dakhini",
    "Dal",
    "Damanis",
    "Dar",
    "Dard",
    "Dareshak",
    "Darzada",
    "Dasti",
    "Daudpota",
    "Daulat Khel",
    "Davi",
    "Dawar",
    "Dawoodi",
    "Dehwar",
    "Derawal",
    "Deshwali",
    "Dhagi",
    "Dhanial",
    "Dharhi",
    "Dhariwal",
    "Dhawad",
    "Dhillon",
    "Dhobi",
    "Dhuldhoya",
    "Dilazak",
    "Dogar",
    "Dogra",
    "Domki",
    "Doodwala",
    "Douli",
    "Duggal",
    "Durrani",
    "Faqir",
    "Fareedi",
    "Farooqi",
    "Firdausi",
    "Gabol",
    "Gadai",
    "Gaddi",
    "Gadhi",
    "Gajani",
    "Gakhar",
    "Galiara",
    "Gandapur",
    "Gardezi",
    "Garha",
    "Garodi",
    "Gashkori",
    "Gautam",
    "Gavandi",
    "Ghaffari",
    "Ghauri",
    "Ghazali",
    "Ghazini",
    "Ghilzai",
    "Ghosi",
    "Ghuman",
    "Gichki",
    "Gilani",
    "Gill",
    "Goan",
    "Gondi",
    "Gopang",
    "Gorgage",
    "Goriya",
    "Gujarati",
    "Gujjar",
    "Gul",
    "Gurmani",
    "Hafiz Khel",
    "Halalkhor",
    "Halaypotra",
    "Halwai",
    "Hamadani",
    "Hashmi",
    "Hasni",
    "Hassan",
    "Hela",
    "Hesbani",
    "Hingora",
    "Hingorja",
    "Hiraj",
    "Hiranbaz",
    "Hundal",
    "Hussain",
    "Hussaini",
    "Hyderabadi",
    "Hyderi",
    "Ibrahim",
    "Idrisi",
    "Indra",
    "Isa Khel",
    "Isfahani",
    "Jadgal",
    "Jadoon",
    "Jafari",
    "Jagirani",
    "Jakhrani",
    "Jalali",
    "Jalbani",
    "Jamali",
    "Jamshidi",
    "Jandran",
    "Jappa",
    "Jarral",
    "Jarwar",
    "Jat",
    "Jatoi",
    "Jats",
    "Jhalawan",
    "Jhojha",
    "Jiskani",
    "Jogi",
    "Johiya",
    "Juneja",
    "Jutt",
    "Kabaria",
    "Kachar",
    "Kadia",
    "Kagzi",
    "Kahloon",
    "Kaira",
    "Kakakhel",
    "Kakar",
    "Kakazai",
    "Kakorvi",
    "Kalhoro",
    "Kalmati",
    "Kalpar",
    "Kalwar",
    "Kalyal",
    "Kamangar",
    "Kambarzahi",
    "Kamboh",
    "Kandera",
    "Karlal",
    "Kasana",
    "Kasgar",
    "Kashani",
    "Kashmiri",
    "Kashmiri Shaikh",
    "Kassar",
    "Kathia",
    "Kayalar",
    "Kayani",
    "Kayastha",
    "Kazmi",
    "Kenagzai",
    "Ker",
    "Kermani",
    "Keyi",
    "Khadem",
    "Khagga",
    "Khakwani",
    "Khalifa",
    "Khalil",
    "Khalol",
    "Khan",
    "Khanzada",
    "Khara",
    "Kharal",
    "Kharoti",
    "Kharral",
    "Khaskheli",
    "Khatana",
    "Khattak",
    "Khawaja",
    "Kheazai",
    "Khetran",
    "Khloro",
    "Khoja",
    "Khokhar",
    "Khorasani",
    "Khosa",
    "Khoso",
    "Khudiadadzai",
    "Khulozai",
    "Khumra",
    "Khushk",
    "Kichlu",
    "Kingharia",
    "Kirmani",
    "Kodava",
    "Kohli",
    "Konkani",
    "Korai",
    "Kuchelai",
    "Kuchis",
    "Kulhaiya",
    "Kundi",
    "Kunjra",
    "Kurd",
    "Labbay",
    "Laghari",
    "Lakhani",
    "Lal",
    "Lalkhani",
    "Langah",
    "Langha",
    "Langhani",
    "Lango",
    "Langra",
    "Langrial",
    "Lanjwani",
    "Lari",
    "Leel",
    "Lehri",
    "Lodhi",
    "Loharani",
    "Lone",
    "Longi",
    "Lund",
    "Maan",
    "Maaple",
    "Machiyar",
    "Madari",
    "Maghdud Khel",
    "Magsi",
    "Mahar",
    "Mahmud Khel",
    "Mahsud",
    "Mahtam",
    "Makhdoom",
    "Makrani",
    "Makwana",
    "Malhotra",
    "Malik",
    "Malkana",
    "Mamund",
    "Mandali",
    "Mandarkia",
    "Manganiar",
    "Mangi",
    "Manihar",
    "Manka",
    "Mansoori",
    "Mappila",
    "Marakkar",
    "Marathi",
    "Marri",
    "Marwat",
    "Mashwanis",
    "Masood",
    "Mazari",
    "Meghwar",
    "Meitei",
    "Memon",
    "Mengal",
    "Meo",
    "Merat",
    "Meta",
    "Mian",
    "Miana",
    "Mighiana",
    "Milki",
    "Minhas",
    "Mir",
    "Mirasi",
    "Mirshikar",
    "Mirwani",
    "Mirza",
    "Miyana",
    "Mohamedzai",
    "Mohmand",
    "Molesalam",
    "Momin",
    "Momna",
    "Montazeri",
    "Mousavi",
    "Mughal",
    "Mugheri",
    "Muhammad Shahi",
    "Muhammadzai",
    "Muhammed Hasni",
    "Mujavir",
    "Muker",
    "Mullagori",
    "Multani",
    "Musakhel",
    "Muslim",
    "Muslim Khatris",
    "Mutwa",
    "Naeem",
    "Nagar",
    "Nagori",
    "Najafi",
    "Nalband",
    "Nanbai",
    "Nanda",
    "Naqqal",
    "Naqvi",
    "Naru",
    "Nat",
    "Nausherwani",
    "Nawayath",
    "Nayak",
    "Niazi",
    "Nishapuri",
    "Nizamani",
    "Node",
    "Noorani",
    "Noorzai",
    "Nothazai",
    "Nutkani",
    "Orakzai",
    "Oriya",
    "Osmani",
    "Ossan",
    "Pamaria",
    "Panar",
    "Panchpiria",
    "Panhwar",
    "Pankhiya",
    "Paracha",
    "Parmar",
    "Pasha",
    "Pasi",
    "Passi",
    "Patani",
    "Patel",
    "Pathan",
    "Pathans",
    "Patni",
    "Pinjara",
    "Pirzada",
    "Pitafi",
    "Popalzai",
    "Protestant",
    "Pusalan",
    "Putliwale",
    "Qadiri",
    "Qaimkhani",
    "Qaisrani",
    "Qalandar",
    "Qalat",
    "Qambrani",
    "Qassab",
    "Qazi",
    "Qizilbash",
    "Qureshi",
    "Qutbi",
    "Rahija",
    "Rahmanzai",
    "Raisani",
    "Rajpar",
    "Rajput",
    "Ramay",
    "Rana",
    "Ranghar",
    "Rangrez",
    "Ranjha",
    "Rath",
    "Rathore",
    "Rayeen",
    "Raza",
    "Razavi",
    "Rehmani",
    "Rind",
    "Rizvi",
    "Rodini",
    "Rowther",
    "Sabzvari",
    "Sadat",
    "Sadozai",
    "Sahi",
    "Sahito",
    "Sahni",
    "Sai",
    "Saifi",
    "Saiqalgar",
    "Sajjadi",
    "Salaat",
    "Salarzai",
    "Salehi",
    "Salmani",
    "Samma",
    "Sandhai",
    "Sangha",
    "Sanghar",
    "Sanjarzai",
    "Sanjrani",
    "Sapera",
    "Sarbani",
    "Sargana",
    "Sarpara",
    "Sasooli",
    "Satti",
    "Sayyed",
    "Sehgal",
    "Sethi",
    "Sethwi",
    "Shah",
    "Shahwani",
    "Shaikh",
    "Shaikhs",
    "Shambhani",
    "Shanzay",
    "Shar",
    "Sheikh",
    "Sherazi",
    "Shershahabadia",
    "Sherzai",
    "Shilmani",
    "Shinwari",
    "Shirani",
    "Sial",
    "Siddiqui",
    "Silawa",
    "Sindhi-Sipahi",
    "Singh",
    "Singiwala",
    "Sipahi",
    "Sistani",
    "Siyal",
    "Solangi",
    "Soomra",
    "Soomro",
    "Sorgar",
    "Sulaymani",
    "Sulemani",
    "Sumalani",
    "Sumbal",
    "Sunni",
    "Suri",
    "Syed",
    "Tadvi",
    "Tahirkheli",
    "Tai",
    "Talpur",
    "Tamil",
    "Tamimi",
    "Tanoli",
    "Taqvi",
    "Tarar",
    "Tareen",
    "Tarkani",
    "Tauqi",
    "Teli",
    "Telugu",
    "Thakurai",
    "Thangal",
    "Thulukkar",
    "Tirmizi",
    "Tiwana",
    "Tokhi",
    "Turabi",
    "Turk",
    "Turkhel",
    "Umar Khel",
    "Umarzai",
    "Umrani",
    "Unar",
    "Usmani",
    "Uthman Khel",
    "Virk",
    "Vora",
    "Vyapari",
    "Wadeyla",
    "Wagher",
    "Wassan",
    "Wasti",
    "Wattoo",
    "Wazir",
    "Wur",
    "Yazdani",
    "Yousafzai",
    "Yusaf Khel",
    "Yusaf Zai",
    "Zaidani",
    "Zaidi",
    "Zain",
    "Zand",
    "Zardari",
    "Zimri",
    "Zubairi"
];

$languages = [
    "Urdu",
    "Punjabi",
    "Saraiki",
    "Sindhi",
    "Pashto",
    "Balochi",
    "Hindko",
    "Brahui",
    "Kashmiri",
    "Shina",
    "English",
    "Arabic",
    "Persian",
    "Turkish",
    "French",
    "German",
    "Spanish",
    "Italian",
    "Chinese",
    "Japanese",
    "Korean",
    "Hindi",
    "Bengali",
    "Gujarati",
    "Marathi",
    "Tamil",
    "Telugu",
    "Malayalam",
    "Kannada",
    "Russian",
    "Portuguese",
    "Dutch",
    "Greek",
    "Thai",
    "Vietnamese",
    "Indonesian",
    "Malay",
    "Swahili",
    "Polish",
    "Ukrainian",
    "Romanian",
    "Czech",
    "Hungarian",
    "Danish",
    "Finnish",
    "Norwegian",
    "Swedish"
];
