<?php
$title = 'Auto Generated Match';
$reportTotal = count($matchRows);
$agmStatusOptions = AutoGeneratedMatchModel::allowedStatuses();
$agmTabCounts = ['all' => $reportTotal];
foreach ($agmStatusOptions as $_st) {
    $agmTabCounts[$_st] = 0;
}
foreach ($matchRows as $_r) {
    $_s = trim((string) ($_r['status'] ?? ''));
    if (isset($agmTabCounts[$_s])) {
        $agmTabCounts[$_s]++;
    }
}
$agmStatusBadgeClass = static function (string $s): string {
    $s = trim($s);
    $map = [
        'Pending' => 'warning',
        'Notified' => 'info',
        'Declined' => 'danger',
        'Accepted' => 'success',
    ];

    return $map[$s] ?? 'secondary';
};
$fmtDt = static function ($raw): string {
    if ($raw === null || $raw === '') {
        return 'N/A';
    }
    $t = strtotime((string) $raw);

    return $t ? date('M j, Y g:i A', $t) : 'N/A';
};
$na = static function ($v) {
    if ($v === null || $v === '') {
        return 'N/A';
    }

    return (string) $v;
};

require __DIR__ . '/partials/header.php';
require __DIR__ . '/partials/sidebar.php';
?>
<link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/admin-manage-members.css">

<div class="admin-main lead-gen-report-page agm-page">
<div class="admin-topbar">
    <div class="admin-topbar-left">
        <button id="mobileMenuBtn" class="mobile-menu-btn" type="button" aria-label="Open menu"><i class="fa fa-bars"></i></button>
        <div class="admin-topbar-title">Manage Auto Generated Match - ALL</div>
    </div>
    <div class="admin-profile" id="adminProfileTrigger">
        <div class="admin-profile-box"><span><?= htmlspecialchars($this->displayadminname()) ?></span><i class="fa fa-user"></i></div>
        <div class="admin-dropdown" id="adminDropdown">
            <a href="<?= BASE_URL ?>/admin/change-password"><i class="fa fa-key"></i> Change Password</a>
            <a href="<?= BASE_URL ?>/admin/logout"><i class="fa fa-sign-out"></i> Logout</a>
        </div>
    </div>
</div>
<main class="admin-page">
<div class="admin-content">
    <div class="container-fluid">
        <?php if (!empty($_SESSION['flash_success'])): ?>
            <div class="alert alert-success alert-dismissible fade show py-2 small mb-3">
                <?= htmlspecialchars($_SESSION['flash_success']);
        unset($_SESSION['flash_success']); ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>
        <?php if (!empty($_SESSION['flash_error'])): ?>
            <div class="alert alert-danger alert-dismissible fade show py-2 small mb-3">
                <?= htmlspecialchars($_SESSION['flash_error']);
        unset($_SESSION['flash_error']); ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>

        <div class="report-panel">
            <div class="report-page-heading mb-3">Manage Auto Generated Match - ALL</div>

            <div class="report-controls-top">
                <div class="report-search-wrap">
                    <div class="input-group lgr-search-group align-items-stretch flex-nowrap">
                        <input type="text" id="agmSearch" class="form-control lgr-search-input" placeholder="Search here...">
                        <button class="btn btn-light border lgr-clear-search flex-shrink-0" type="button" id="agmClearSearch" aria-label="Clear"><i class="fa fa-times"></i></button>
                        <button class="btn btn-primary flex-shrink-0" type="button" id="agmSearchBtn"><i class="bi bi-search me-1"></i> Search</button>
                    </div>
                </div>
            </div>
            <div class="report-show-row mt-2 mb-2">
                <span class="show-entry-wrap"><label class="me-2 mb-0">Show</label><select id="agmShowEntries" class="form-select form-select-sm d-inline-block w-auto"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="9999">All</option></select><label class="ms-2 mb-0">Entries</label></span>
            </div>

            <ul class="nav nav-tabs lgr-tabs mb-0 agm-status-tabs" role="tablist">
                <li class="nav-item">
                    <button type="button" class="nav-link active agm-tab" data-agm-tab="all" id="agmTabAll">All <small>(<?= (int) $agmTabCounts['all'] ?>)</small></button>
                </li>
                <?php foreach ($agmStatusOptions as $tabLabel): ?>
                <li class="nav-item">
                    <button type="button" class="nav-link agm-tab" data-agm-tab="<?= htmlspecialchars($tabLabel, ENT_QUOTES, 'UTF-8') ?>" id="agmTab<?= preg_replace('/\W+/', '', $tabLabel) ?>"><?= htmlspecialchars($tabLabel) ?> <small>(<?= (int) ($agmTabCounts[$tabLabel] ?? 0) ?>)</small></button>
                </li>
                <?php endforeach; ?>
            </ul>

            <div class="table-responsive lgr-table-wrap">
                <table class="table table-striped table-hover table-bordered mb-0 align-middle lgr-table">
                    <thead class="table-dark">
                        <tr>
                            <th>Male Member ID</th>
                            <th>Female Member ID</th>
                            <th class="lgr-th-sort">Match Score <i class="fa fa-sort-desc ms-1" aria-hidden="true"></i></th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th class="text-center" style="width:72px">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="agmTbody">
                        <?php foreach ($matchRows as $R):
                            $rowStatus = trim((string) ($R['status'] ?? ''));
                            $searchBlob = strtolower(trim(implode(' ', [
                                (string) ($R['male_user_id'] ?? ''),
                                (string) ($R['female_user_id'] ?? ''),
                                (string) ($R['match_score'] ?? ''),
                                $rowStatus,
                                $fmtDt($R['created_at'] ?? null),
                            ])));
                            $rid = (int) ($R['id'] ?? 0);
                            ?>
                        <tr class="agm-row" data-search="<?= htmlspecialchars($searchBlob, ENT_QUOTES, 'UTF-8') ?>" data-match-status="<?= htmlspecialchars($rowStatus, ENT_QUOTES, 'UTF-8') ?>">
                            <td><?= htmlspecialchars((string) ($R['male_user_id'] ?? '')) ?></td>
                            <td><?= htmlspecialchars((string) ($R['female_user_id'] ?? '')) ?></td>
                            <td><?= htmlspecialchars($na($R['match_score'] ?? '')) ?></td>
                            <td class="align-middle" style="min-width:11rem">
                                <div class="d-flex flex-column flex-sm-row align-items-stretch align-items-sm-center gap-1">
                                    <span class="badge bg-<?= htmlspecialchars($agmStatusBadgeClass($rowStatus), ENT_QUOTES, 'UTF-8') ?> align-self-start"><?= htmlspecialchars($rowStatus !== '' ? $rowStatus : 'N/A') ?></span>
                                    <form method="POST" action="<?= BASE_URL ?>/admin/reports/match-making/auto-match-email/auto-generated-match/status" class="flex-grow-1">
                                        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'] ?? '') ?>">
                                        <input type="hidden" name="id" value="<?= $rid ?>">
                                        <label class="visually-hidden" for="agm-st-<?= $rid ?>">Update status (auto_generated_matches)</label>
                                        <select name="status" id="agm-st-<?= $rid ?>" class="form-select form-select-sm" title="Updates auto_generated_matches.status" onchange="this.form.submit()">
                                            <?php
                                            $opts = $agmStatusOptions;
                                            if ($rowStatus !== '' && !in_array($rowStatus, $opts, true)) {
                                                $opts = array_merge([$rowStatus], $opts);
                                            }
                                            foreach ($opts as $opt):
                                                ?>
                                                <option value="<?= htmlspecialchars($opt, ENT_QUOTES, 'UTF-8') ?>"<?= $opt === $rowStatus ? ' selected' : '' ?>><?= htmlspecialchars($opt) ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </form>
                                </div>
                            </td>
                            <td><?= htmlspecialchars($fmtDt($R['created_at'] ?? null)) ?></td>
                            <td class="text-center">
                                <form method="POST" action="<?= BASE_URL ?>/admin/reports/match-making/auto-match-email/auto-generated-match/delete" class="d-inline" onsubmit="return confirm('Delete this record?');">
                                    <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'] ?? '') ?>">
                                    <input type="hidden" name="id" value="<?= $rid ?>">
                                    <button type="submit" class="btn btn-link btn-sm text-danger p-0 lgr-trash" title="Delete"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="lgr-footer-bar d-flex flex-wrap flex-md-nowrap justify-content-between align-items-center gap-2 mt-2 pt-2 px-2 pb-3">
                <div class="small text-muted flex-shrink-0" id="agmInfo">Showing 0 to 0 of 0 entries</div>
                <nav class="flex-shrink-0" aria-label="Pagination">
                    <ul class="pagination pagination-sm mb-0 amch-pagination" id="agmPagination"></ul>
                </nav>
            </div>
        </div>
    </div>
</div>
</main>
</div>

<style>.agm-status-tabs .nav-link.agm-tab{border:0;background:transparent;cursor:pointer}.agm-status-tabs .nav-link.agm-tab.active{font-weight:600}</style>
<script>
(function(){
    const searchInput = document.getElementById('agmSearch');
    const rows = () => Array.from(document.querySelectorAll('.agm-row'));
    const showSel = document.getElementById('agmShowEntries');
    const infoEl = document.getElementById('agmInfo');
    const pagEl = document.getElementById('agmPagination');
    let currentPage = 1;
    let activeMatchTab = 'all';

    function filtered() {
        const q = (searchInput && searchInput.value ? searchInput.value : '').toLowerCase().trim();
        return rows().filter(function(r) {
            if (activeMatchTab !== 'all') {
                const st = (r.getAttribute('data-match-status') || '').trim();
                if (st !== activeMatchTab) return false;
            }
            return !q || (r.getAttribute('data-search') || '').indexOf(q) !== -1;
        });
    }

    document.querySelectorAll('.agm-tab').forEach(function(btn) {
        btn.addEventListener('click', function() {
            activeMatchTab = (btn.getAttribute('data-agm-tab') || 'all');
            document.querySelectorAll('.agm-tab').forEach(function(b) { b.classList.remove('active'); });
            btn.classList.add('active');
            currentPage = 1;
            render();
        });
    });

    function appendPageLink(text, targetPage, isActive, isDisabled) {
        const li = document.createElement('li');
        li.className = 'page-item';
        if (isActive) li.classList.add('active');
        if (isDisabled) li.classList.add('disabled');
        const isStatic = isActive || isDisabled;
        const el = document.createElement(isStatic ? 'span' : 'a');
        el.className = 'page-link';
        el.textContent = text;
        if (!isStatic) {
            el.href = '#';
            el.addEventListener('click', function(e) {
                e.preventDefault();
                currentPage = targetPage;
                render();
            });
        }
        li.appendChild(el);
        pagEl.appendChild(li);
    }

    function render() {
        const all = filtered();
        const total = all.length;
        let per = parseInt(showSel && showSel.value ? showSel.value : '10', 10);
        if (isNaN(per) || per < 1) per = 10;
        let pages = 0;
        if (total === 0) { pages = 0; currentPage = 1; }
        else if (per >= 9999) { pages = 1; }
        else { pages = Math.max(1, Math.ceil(total / per)); }
        if (currentPage > pages && pages > 0) currentPage = pages;
        if (currentPage < 1) currentPage = 1;
        const start = total === 0 ? 0 : (per >= 9999 ? 1 : (currentPage - 1) * per + 1);
        const end = total === 0 ? 0 : (per >= 9999 ? total : Math.min(currentPage * per, total));

        rows().forEach(function(r) { r.style.display = 'none'; });
        if (per >= 9999) {
            all.forEach(function(r) { r.style.display = ''; });
        } else {
            all.slice((currentPage - 1) * per, currentPage * per).forEach(function(r) { r.style.display = ''; });
        }

        infoEl.textContent = total === 0 ? 'Showing 0 to 0 of 0 entries' : ('Showing ' + start + ' to ' + end + ' of ' + total + ' entries');

        pagEl.innerHTML = '';
        if (pages <= 0) return;

        appendPageLink('Previous', currentPage - 1, false, currentPage === 1);
        for (let p = 1; p <= pages; p++) {
            appendPageLink(String(p), p, p === currentPage, false);
        }
        appendPageLink('Next', currentPage + 1, false, currentPage === pages);
        appendPageLink('Last', pages, false, currentPage === pages);
    }

    searchInput && searchInput.addEventListener('keyup', function() { currentPage = 1; render(); });
    document.getElementById('agmSearchBtn') && document.getElementById('agmSearchBtn').addEventListener('click', function() { currentPage = 1; render(); });
    document.getElementById('agmClearSearch') && document.getElementById('agmClearSearch').addEventListener('click', function() {
        searchInput.value = ''; currentPage = 1; render();
    });
    showSel && showSel.addEventListener('change', function() { currentPage = 1; render(); });
    render();
})();
</script>

<?php require __DIR__ . '/partials/footer.php'; ?>
