<?php

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/../models/AutoMatchCronHistoryModel.php';
require_once __DIR__ . '/../models/AutoGeneratedMatchModel.php';
require_once __DIR__ . '/../models/Admin.php';

class AdminAutoMatchCronController
{
    protected $model;
    /** @var AutoGeneratedMatchModel */
    protected $generatedModel;
    protected $admin;

    public const CRON_HISTORY_URL = '/admin/reports/match-making/auto-match-email/cron-history';
    public const AUTO_GEN_URL = '/admin/reports/match-making/auto-match-email/auto-generated-match';

    public function __construct()
    {
        if (empty($_SESSION['admin_id'])) {
            header('Location: ' . BASE_URL . '/admin/login');
            exit;
        }
        $this->admin = new Admin();
        $this->model = new AutoMatchCronHistoryModel();
        $this->generatedModel = new AutoGeneratedMatchModel();
    }

    public function displayadminname(): string
    {
        $row = $this->admin->findById($_SESSION['admin_id']);

        return $row ? (string) $row['name'] : 'Admin';
    }

    public function cronHistory(): void
    {
        if (empty($_SESSION['csrf_token'])) {
            $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
        }
        $cronRows = $this->model->allRows();
        require __DIR__ . '/../views/admin/auto_match_cron_history.php';
    }

    public function cronHistoryDelete(): void
    {
        $redir = BASE_URL . self::CRON_HISTORY_URL;
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            header('Location: ' . $redir);
            exit;
        }
        $token = $_POST['csrf_token'] ?? '';
        if (empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $token)) {
            $_SESSION['flash_error'] = 'Invalid request token.';
            header('Location: ' . $redir);
            exit;
        }
        $id = (int) ($_POST['id'] ?? 0);
        if ($id < 1) {
            header('Location: ' . $redir);
            exit;
        }
        if ($this->model->find($id)) {
            $this->model->delete($id);
            $_SESSION['flash_success'] = 'Record removed.';
        }
        header('Location: ' . $redir);
        exit;
    }

    public function autoGeneratedMatch(): void
    {
        if (empty($_SESSION['csrf_token'])) {
            $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
        }
        $matchRows = $this->generatedModel->allRows();
        require __DIR__ . '/../views/admin/auto_generated_match.php';
    }

    public function autoGeneratedMatchDelete(): void
    {
        $redir = BASE_URL . self::AUTO_GEN_URL;
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            header('Location: ' . $redir);
            exit;
        }
        $token = $_POST['csrf_token'] ?? '';
        if (empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $token)) {
            $_SESSION['flash_error'] = 'Invalid request token.';
            header('Location: ' . $redir);
            exit;
        }
        $id = (int) ($_POST['id'] ?? 0);
        if ($id < 1) {
            header('Location: ' . $redir);
            exit;
        }
        if ($this->generatedModel->find($id)) {
            $this->generatedModel->delete($id);
            $_SESSION['flash_success'] = 'Record removed.';
        }
        header('Location: ' . $redir);
        exit;
    }

    /** Legacy URL → new Reports path */
    public function legacyCronHistoryRedirect(): void
    {
        header('Location: ' . BASE_URL . self::CRON_HISTORY_URL, true, 302);
        exit;
    }
}
