<?php

class AutoGeneratedMatchModel
{
    private $db;

    public function __construct()
    {
        $this->db = Database::getInstance()->pdo();
        $this->ensureTable();
    }

    private function ensureTable(): void
    {
        $this->db->exec("
            CREATE TABLE IF NOT EXISTS auto_generated_matches (
                id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                male_user_id INT UNSIGNED NOT NULL,
                female_user_id INT UNSIGNED NOT NULL,
                match_score VARCHAR(20) DEFAULT NULL,
                status VARCHAR(50) NOT NULL DEFAULT 'Pending',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                INDEX idx_created (created_at),
                INDEX idx_status (status)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        ");
        $this->seedIfEmpty();
    }

    private function seedIfEmpty(): void
    {
        $n = (int) $this->db->query('SELECT COUNT(*) FROM auto_generated_matches')->fetchColumn();
        if ($n > 0) {
            return;
        }
        $statuses = ['Pending', 'Notified', 'Declined', 'Accepted'];
        $stmt = $this->db->prepare('
            INSERT INTO auto_generated_matches (male_user_id, female_user_id, match_score, status)
            VALUES (?, ?, ?, ?)
        ');
        for ($i = 0; $i < 18; $i++) {
            $m = 100 + $i * 2;
            $f = 200 + $i * 2 + 1;
            $score = sprintf('%.1f', 50 + ($i % 45) + ($i * 0.13));
            $st = $statuses[$i % count($statuses)];
            $stmt->execute([$m, $f, $score, $st]);
        }
    }

    public function allRows(): array
    {
        $stmt = $this->db->query('
            SELECT * FROM auto_generated_matches
            ORDER BY created_at DESC, id DESC
        ');

        return $stmt->fetchAll(PDO::FETCH_ASSOC) ?: [];
    }

    public function find(int $id): ?array
    {
        $stmt = $this->db->prepare('SELECT * FROM auto_generated_matches WHERE id = ? LIMIT 1');
        $stmt->execute([$id]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        return $row ?: null;
    }

    public function delete(int $id): bool
    {
        $stmt = $this->db->prepare('DELETE FROM auto_generated_matches WHERE id = ?');

        return $stmt->execute([$id]);
    }
}
